import 'dart:io';
import 'package:ffmpeg_kit_flutter_full_gpl/ffmpeg_kit.dart';
import 'package:ffmpeg_kit_flutter_full_gpl/return_code.dart';
import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

class ExportService {
  /// Converts the generated audio file to a high-quality MP3 and provides sharing options.
  Future<String?> exportToMp3(String inputPath) async {
    final directory = await getApplicationDocumentsDirectory();
    final outputPath = "${directory.path}/MaxRegner_Studio_${DateTime.now().millisecondsSinceEpoch}.mp3";

    // Use FFmpeg to encode to high-quality MP3 (320kbps)
    // -i: input file
    // -codec:a libmp3lame: use MP3 encoder
    // -b:a 320k: 320kbps bitrate
    final session = await FFmpegKit.execute("-i \"$inputPath\" -codec:a libmp3lame -b:a 320k \"$outputPath\"");
    final returnCode = await session.getReturnCode();

    if (ReturnCode.isSuccess(returnCode)) {
      return outputPath;
    } else {
      final logs = await session.getLogs();
      print("FFmpeg Error: ${logs.map((l) => l.getMessage()).join('\n')}");
      return null;
    }
  }

  /// Shares the exported MP3 file using the system share sheet.
  Future<void> shareMp3(String filePath) async {
    final file = XFile(filePath);
    await Share.shareXFiles([file], text: 'Check out my new track generated by MaxRegner AI!');
  }
}
